backend/src/main/java/com/devu/backend/common/Messages.java, backend/src/main/java/com/devu/backend/common/exception/BusinessException.java, backend/src/main/java/com/devu/backend/common/exception/EmailConfirmNotCompleteException.java, backend/src/main/java/com/devu/backend/common/exception/PasswordNotSameException.java, backend/src/main/java/com/devu/backend/common/exception/UserNotFoundException.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/repository/UserRepository.java, backend/src/main/java/com/devu/backend/service/UserService.java
- API : POST  /signin , Content-type : JSON
1) NO_USER_MESSAGE
2) NO_EMAIL_CONFIRM
3) PASSWORD_NOT_EQUAL
=> fucn:Login,Exception

backend/src/main/java/com/devu/backend/common/Messages.java, backend/src/main/java/com/devu/backend/common/exception/AlreadyExistsEmailException.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/entity/User.java, backend/src/main/java/com/devu/backend/service/UserService.java, backend/src/main/java/com/devu/backend/service/email/EmailServiceImpl.java
- 이메일 인증번호 재전송하는 로직 작성
- 로직 순서 : 이메일 입력 및 전송(form-data) => 이메일 인증번호 전송 => 인증번호 입력 => 인증번호 전송(form-data) => **Confirm**
- **페이지에서 '재전송' 버튼 누를 시**에 대한 예외처리 진행 => User Entity의 updateAuthKey()를 이용한 **Dirty Checking** 활용
- 추가로 POST : /key를 통해  인증받을 경우에도 **Dirty Checking**를 통해 emailConfirm 불리언 값을 변경
=> func:Email Resend Validation

backend/src/main/java/com/devu/backend/config/AsyncConfig.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/service/EmailService.java, backend/src/main/java/com/devu/backend/service/email/EmailService.java
- 이메일 전송 속도 개선을 위해 Async 방식 적용
=> update:Async Email Sending

backend/build.gradle, backend/src/main/java/com/devu/backend/config/AppConfig.java, backend/src/main/java/com/devu/backend/config/SecurityConfig.java, backend/src/main/java/com/devu/backend/config/auth/UserDetailsImpl.java, backend/src/main/java/com/devu/backend/config/auth/UserDetailsServiceImpl.java, backend/src/main/java/com/devu/backend/config/auth/token/JwtAuthenticationFilter.java, backend/src/main/java/com/devu/backend/config/auth/token/TokenService.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/service/UserService.java
=> feat: Set Security, Jwt 

docker-compose.yml, frontend/Dockerfile, frontend/conf/conf.d/defualt.conf
- 기존의 방식에 nginx 이미지 받아와서 설치 및 config까지 설정
- volumes 수정 : Volume Container의 Path를 알려준다
- 포트 수정 : `3000:3000` 에서 `80:80`으로 수정
- 일반적인 도커 컨테이너는 컨테이너 내부에서 데이터를 관리하기에 로그 및 중요한 데이터들이 컨테이너가 파괴될수 날라갈 수 있다...
- 이러한 데이터들을 보관하기 위한 곳이 **Volume Container**이다.
=> update:React Docker image with nginx

backend/src/main/java/com/devu/backend/entity/GeneralPost.java, backend/src/main/java/com/devu/backend/entity/Image.java, backend/src/main/java/com/devu/backend/entity/Post.java
=> feat: Add Post, Image Entity

backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/entity/User.java, backend/src/main/java/com/devu/backend/repository/UserRepository.java, backend/src/main/java/com/devu/backend/service/UserService.java
- Email 중복 시, 예외처리 badRequest로 response 전송
- username 중복 예외처리
=> update : Exception

backend/src/main/java/com/devu/backend/common/Messages.java, backend/src/main/java/com/devu/backend/common/exception/PostNotFoundException.java, backend/src/main/java/com/devu/backend/config/SecurityConfig.java, backend/src/main/java/com/devu/backend/controller/post/PostController.java, backend/src/main/java/com/devu/backend/controller/post/RequestPostUpdateDto.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/entity/User.java, backend/src/main/java/com/devu/backend/entity/post/Post.java, backend/src/main/java/com/devu/backend/repository/UserRepository.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/java/com/devu/backend/service/UserService.java, backend/src/main/resources/application-local.yml
=> feat: Add Post feat(Update, Delete)

frontend/src/components/Register/Register.js
- REST API response 값 받아와서 alert 창 출력함
=> fix: 회원가입- 이메일 중복 확인

backend/src/main/java/com/devu/backend/controller/post/PostController.java, backend/src/main/java/com/devu/backend/controller/post/ResponsePostDto.java, backend/src/main/java/com/devu/backend/repository/PostRepository.java, backend/src/main/java/com/devu/backend/service/PostService.java
- GET : /commnity/chats/{id} 
- PathVariable로 조회할 Post의 ID 넘겨야합니다
- 해당 ID값은 GET /communtity/chats으로 전송하는 페이징 구현된 DTO의 ID에 싣어놓았습니다.
- 해당 API 전송 시 hit 자동으로 +1 기능 추가
=> update : Post 단건 조회

backend/src/main/java/com/devu/backend/config/s3/S3Uploader.java, backend/src/main/java/com/devu/backend/controller/post/PostController.java, backend/src/main/java/com/devu/backend/service/PostService.java
=> update:Study and Chat Image function

backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/service/UserService.java, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java
=> test: Test UserController

backend/src/main/java/com/devu/backend/common/Messages.java, backend/src/main/java/com/devu/backend/common/exception/PasswordDupException.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/java/com/devu/backend/service/UserService.java, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java, backend/src/test/java/com/devu/backend/service/UserServiceTest.java
- 이전 비밀번호 중복 예외처리
- fix: UserService 단위 테스트
=> update:UserController Refactoring

backend/src/main/java/com/devu/backend/config/SecurityConfig.java, backend/src/main/java/com/devu/backend/config/WebConfig.java, backend/src/main/java/com/devu/backend/config/auth/token/JwtAuthenticationFilter.java, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/controller/user/UserDTO.java, backend/src/main/java/com/devu/backend/service/CookieService.java, backend/src/main/java/com/devu/backend/service/UserService.java
Logout, silent-refresh 추가
*변경사항 : accesstoken header로 전달 (로그인때나, 재발급 받을때)
UserDto에서 token column 삭제
=> feat: Add Logout

backend/src/main/java/com/devu/backend/api/comment/CommentApiController.java, backend/src/main/java/com/devu/backend/api/comment/CommentResponseDto.java, backend/src/main/java/com/devu/backend/api/comment/CommentUpdateRequestDto.java, backend/src/main/java/com/devu/backend/config/SecurityConfig.java, backend/src/main/java/com/devu/backend/entity/Comment.java, backend/src/main/java/com/devu/backend/repository/CommentRepository.java, backend/src/main/java/com/devu/backend/service/CommentService.java, backend/src/test/java/com/devu/backend/service/CommentServiceTest.java
=> feat: Add Function that Deletes Hierarchical comments

frontend/.env.development, frontend/.env.product, frontend/src/components/Forum/Board/Board.js, frontend/src/components/Forum/Board/Modify.js, frontend/src/components/Forum/Board/PostView.js, frontend/src/components/Forum/Board/Write.js, frontend/src/components/Navbar/ChangePassword.js, frontend/src/components/Navbar/ChangePasswordModal.js, frontend/src/components/Navbar/LoginButton.js, frontend/src/components/Register/Register.js
frontend 디렉토리에 .env.product, .env.development 파일 추가해서 해결함.
[참고]: https://velog.io/@ezae/React-build%EB%B0%B0%ED%8F%AC-%ED%9B%84-api-response-%EB%AC%B8%EC%A0%9C
=> fix: Request URL

backend/src/main/java/com/devu/backend/service/CommentService.java
=> fix: fix the logic of deleting recomment

frontend/.env.product, frontend/.env.production, frontend/src/index.js
.env.product -> .env.production
=> rename: .env.production

backend/src/main/java/com/devu/backend/api/comment/CommentApiController.java, backend/src/main/java/com/devu/backend/api/comment/recomment/ReCommentCreateRequestDto.java, backend/src/main/java/com/devu/backend/api/comment/recomment/ReCommentResponseDto.java, backend/src/main/java/com/devu/backend/api/like/LikeApiController.java, backend/src/main/java/com/devu/backend/api/like/ResponseLikeDto.java, backend/src/main/java/com/devu/backend/api/password/ChangePasswordApiController.java, backend/src/main/java/com/devu/backend/api/status/RequestStatusDto.java, backend/src/main/java/com/devu/backend/api/status/ResponseStatusDto.java, backend/src/main/java/com/devu/backend/api/status/StatusApiController.java, backend/src/main/java/com/devu/backend/common/Messages.java, backend/src/main/java/com/devu/backend/common/exception/UserNotMatchException.java, backend/src/main/java/com/devu/backend/config/SecurityConfig.java, backend/src/main/java/com/devu/backend/controller/post/PostRequestUpdateDto.java, backend/src/main/java/com/devu/backend/entity/Like.java, backend/src/main/java/com/devu/backend/entity/Tag.java, backend/src/main/java/com/devu/backend/entity/post/Post.java, backend/src/main/java/com/devu/backend/service/EmailService.java, backend/src/main/java/com/devu/backend/service/LikeService.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/resources/application.yml
- Like api 에러 수정
- Status 변경 api 추가 : Solved일 경우, UnSolved로 Unsolved는 Solved로 변경
- StatusRequestDto (username,postId)
=> fix and update

backend/src/main/java/com/devu/backend/api/mypage/MyPageApiController.java, backend/src/main/java/com/devu/backend/controller/user/UserRequestUpdateDto.java, backend/src/main/java/com/devu/backend/entity/User.java, backend/src/main/java/com/devu/backend/entity/post/Post.java, backend/src/main/java/com/devu/backend/repository/PostRepository.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/java/com/devu/backend/service/UserService.java, backend/src/test/java/com/devu/backend/repository/PostRepositoryTest.java, backend/src/test/java/com/devu/backend/repository/UserRepositoryTest.java
#My Page Api Update
- 하나의 List에 chat,study,question이 PostResponseDto 형태로 담겨져 리턴
- tag와 status가 모두 없으면 해당 객체는 chat
- studyStatus가 존재하면 해당 객체는 study
- questinoStatus가 존재하면 해당 객체는 question
- 분류를 통해서 랜더링 부탁드립니다.
- User의 posts 리스트에 CascadeOption.ALL과 oprphanRemoval = True 옵션을 주었기에 User 삭제시 모든 Post들이 함께 삭제됨
- Post가 삭제되면 모든 Likes,Comments,Images,PostTag도 연쇄적으로 삭제됨
- Username변경 api
- 추후에 프로필 이미지 도입시 해당 api에 함께 싣을 예정
=> update:MyPage API

backend/src/main/java/com/devu/backend/api/mypage/MyPageApiController.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/java/com/devu/backend/service/UserService.java
- 기존의 username을 path variable로 받아서 user를 레포지토리에서 직접 찾는 방법 개선
- 대신 모든 Mypage Api에 로그인된 유저의 **X-AUTH-ACCESS-TOKEN**을 request 헤더에 싣어서 보내야합니다.
- 이외의 사용법은 기존과 동일 -> notion 참고
=> update:Mypage using @AuthenticationPricipal and UserDetailsImpl

frontend/src/App.js, frontend/src/components/Forum/Chats/Chats.js, frontend/src/components/Forum/Chats/PostView.js, frontend/src/components/Forum/Studies/Studies.js, frontend/src/components/Forum/Studies/Write.js, frontend/src/components/Forum/Studies/write.css
- 자유게시판, 스터디구인 게시판 페이지네이션  /community/chats/size api 받아와서 완성
- 자유게시판 게시글의 작성자가 아니면 수정하기, 삭제하기 버튼 안보이게 수정
- 스터디구인 게시판 글작성 페이지 구현
- 자유게시판 좋아요 기능 getMapping도 있어야 할 것 같음!
=> fix: chat•study pagination, chat postview, study write

backend/src/main/java/com/devu/backend/api/mypage/MyPageApiController.java, backend/src/main/java/com/devu/backend/api/weather/WeatherApiController.java, backend/src/main/java/com/devu/backend/api/weather/WeatherRequestDto.java
- 기본값으로 경상북도 북부동의 정보를 알려줍니다.(현재 영남대 위치)
```
@Getter
public class WeatherRequestDto {
private String baseDate; //ex) 220513
private String baseTime; //ex) 0200
/*
* baseTime 가능한 시간 -> 앞뒤로 1시간 30분으로 나누기
* 0200 -> 00:30 ~ 03:30
* 0500 -> 03:30 ~ 06:30
* 0800 -> 06:30 ~ 09:30
* 1100 -> 09:30 ~ 12:30
* 1400 -> 12:30 ~ 15:30
* 1700 -> 15:30 ~ 18:30
* 2000 -> 18:30 ~ 21:30
* 2300 -> 21:30 ~ 00:30
* */
}
```
- 위와 같은 RequestDto를 통해 날씨 정보 조회 요청을 한 날짜 및 시간을 String 형태로 보내야합니다.
- 특히 baseTime의 경우 **위 주석의 조건에 맞춰** 보내주세요
- 응답의 결과로 받는 데이터의 경우 해당 날씨 데이터의 catergory와 value를 key-value쌍으로 돌려줍니다.
- 해당 정보를 통해 현재 날씨를 파악할 수 있습니다.
- 날씨 데이터의 상세한 정보는 [여기서](https://www.data.go.kr/iim/api/selectAPIAcountView.do) 확인 가능합니다.
- **GET** : /api/weather
=> update:Weather API

backend/src/main/java/com/devu/backend/config/SecurityConfig.java, backend/src/main/java/com/devu/backend/config/auth/token/JwtAuthenticationFilter.java, backend/src/main/java/com/devu/backend/service/UserService.java
여러번 요청이 생성되어 GenericFilter -> OncePerRequestFilter로 변경
+로직수정
=> fix: fix Jwt

frontend/src/components/ChatBot/ChatBot.js, frontend/src/components/Forum/Chats/ChatsView.js, frontend/src/components/Forum/Questions/QuestionsView.js, frontend/src/components/Forum/Studies/StudiesView.js
글 작성자가 아닌 댓글 작성자가 본인 댓글을 작성하도록 수정 필요
=> feat: comment delete incomplete

backend/src/main/java/com/devu/backend/api/comment/CommentApiController.java, backend/src/main/java/com/devu/backend/controller/post/PostResponseDto.java, backend/src/main/java/com/devu/backend/service/CommentService.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/resources/application.yml
기존의 Commnet들을 전부 리스트로 리턴하는 방식에서 CommenetResponseDto를 리스트로 반환하는 방식으로 변경
=> fix: PostResponse 리턴시 Comment 대신 CommnetResponseDto 반환

frontend/src/components/MyPage/MyPage.js
- 마이페이지 처음 접속하면 작성한 글 -> 스터디구인란 먼저 보임
- 버튼 하나씩 누르면 해당하는 게시판 글 렌더링됨
- 자유게시판은 글 상태 필요 없을 것 같아서 <th width="150">상태</th> 안보이게 함
- 추후에 시간 포맷 다시 변경해야 함
=> feat: myPage rendering

frontend/src/components/Jobs/Jobs.js, frontend/src/components/MyPage/MyPage.js, frontend/src/components/MyPage/myPage.css
- 마이페이지 글 제목에 마우스 커서 css 바꿈
- 회사별로 취업 정보 따로 불러오기
=> fix: mypage cursor css, jobs by company

frontend/src/components/Navbar/ChangePasswordModal.js, frontend/src/components/Navbar/changePasswordModal.css, frontend/src/components/Navbar/loginModal.css
- 로그인 모달에 있는 비밀번호 찾기 누르면 보이는 비밀번호 찾기 모달 css 변경
=> fix: findPassword css

frontend/src/components/Forum/Chats/Chats.js, frontend/src/components/Forum/Chats/ChatsView.js, frontend/src/components/Forum/Questions/Questions.js, frontend/src/components/Forum/Questions/QuestionsView.js, frontend/src/components/Forum/Studies/Studies.js, frontend/src/components/Forum/Studies/StudiesView.js, frontend/src/components/Navbar/ChangePasswordModal.js
문제점
- 좋아요 -> 새로고침 -> 좋아요 연속해서 하면 마지막 좋아요 작동 안됨
- useState(false)로 처음 isLike 초기화 했었는데 이렇게 하면 true, false 두 가지 상태 밖에 없기 때문에 새로고침한 뒤 좋아요 누르면 useEffect가 작동이 안되기 때문에 좋아요 렌더링이 안되는 것이 맞음
해결방법
- 그래서 useState(1)로 초기화하고, 좋아요 누르면 set함수로 isLike+1, 좋아요 해제하면 isLike-1로 설정해 상태를 총 3가지로 만듦
=> fix: Post Like function

backend/src/main/java/com/devu/backend/service/PositionService.java
fix:MySql Emoji error by removeEmoji method
=> fix:MySql Emoji error by removeEmoji method

frontend/src/components/Forum/Chats/ChatsView.js, frontend/src/components/Forum/Chats/Modify.js, frontend/src/components/Forum/Questions/QuestionsModify.js, frontend/src/components/Forum/Studies/StudiesModify.js
- post delete 오류 -> 오타 있어서 오류가 있었고 해결함.
- post modify 오류 -> 수정하기 페이지 로드했을 때 글 제목, 글 내용 정보를 바로 postContent에 저장하지 않아 글 제목, 글 내용을 건들지 않으면 수정이 안되는 오류가 있었고 해결함. 태그 수정은 좀 더 살펴봐야 함(조건적으로 작동함)
=> fix: post modify, delete

backend/src/main/java/com/devu/backend/api/mypage/MyPageApiController.java, backend/src/main/java/com/devu/backend/service/UserService.java
=> feat: Add the logic of deleting cookies to the logic of deleting user

backend/Dockerfile
update:Dockerfile for jenkins2
=> update:Dockerfile for jenkins#2

backend/.gitignore, backend/src/main/java/com/devu/backend/config/auth/token/JwtAuthenticationFilter.java, backend/src/main/java/com/devu/backend/config/auth/token/TokenService.java, backend/src/main/resources/application.yml, backend/src/test/java/com/devu/backend/config/auth/UserDetailsServiceImplTest.java, backend/src/test/java/com/devu/backend/config/auth/token/TokenServiceTest.java
[#191] 코드 리팩터링 및 테스트코드를 위한 함수 추가
- 리팩터링
-  validateTokenExceptExpiration -> validateToken
-  jwt관련 값들 설정파일에서 @Value 주입
- TokenService에 테스트코드를 위한 함수 추가
@Value를 위한 테스트코드를 위한 함수가 맞는것인가..?
=> refactor: 코드 리팩터링 및 테스트코드를 위한 함수 추가

backend/BOOT-INF/classes/static/docs/api.html, backend/build.gradle, backend/src/docs/asciidoc/api.adoc, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/main/resources/static/docs/api.html, backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java, backend/src/test/java/com/devu/backend/service/PostServiceTest.java
Post 수정, 삭제 테스트 및 Spring Rest Docs 적용
- PostService 수정, 삭제 테스트
- Spring Rest Docs 세팅
- PostController 수정, 삭제 테스트
=> test: Post 수정, 삭제 테스트 및 Spring Rest Docs 적용

backend/src/test/java/com/devu/backend/BackendApplicationTests.java, backend/src/test/java/com/devu/backend/config/TestConfig.java, backend/src/test/java/com/devu/backend/config/auth/UserDetailsServiceImplTest.java, backend/src/test/java/com/devu/backend/config/auth/token/TokenServiceTest.java, backend/src/test/java/com/devu/backend/config/s3/S3UploaderTest.java, backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java, backend/src/test/java/com/devu/backend/repository/CommentRepositoryTest.java, backend/src/test/java/com/devu/backend/repository/PostRepositoryTest.java, backend/src/test/java/com/devu/backend/repository/TagRepositoryTest.java, backend/src/test/java/com/devu/backend/repository/UserRepositoryTest.java, backend/src/test/java/com/devu/backend/service/PostServiceTest.java, backend/src/test/java/com/devu/backend/service/UserServiceTest.java, backend/src/test/resources/application-test.yml
=> fix:테스트 코드 용 인메모리 DB 사용

backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java
=> fix:PostControllerTest

backend/src/main/java/com/devu/backend/config/SecurityConfig.java
=> fix:CORS 에러

backend/src/main/java/com/devu/backend/config/SecurityConfig.java
=> fix:CORS 에러(2)

frontend/Dockerfile, frontend/nginx.conf
- Dockerfile 수정
- nginx.conf 추가
=> feat:SSL(1)

frontend/nginx.conf
=> feat:SSL(4)

frontend/nginx.conf
=> feat:SSL(5)

backend/src/main/java/com/devu/backend/config/SecurityConfig.java
=> fix:CORS by https

frontend/Dockerfile, frontend/conf/conf.d/defualt.conf
- nginx.conf 수정 방식 -> conf.d의 default.conf 수정 방식으로 변경
=> feat:SSL(6)

backend/src/docs/asciidoc/api.adoc, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java
docs: UserControllerTest API 문서화
=> docs: UserControllerTest API 문서화

backend/build.gradle, backend/src/main/java/com/devu/backend/controller/user/UserController.java, backend/src/main/java/com/devu/backend/controller/user/UserEmailRequestDto.java, backend/src/main/java/com/devu/backend/controller/validation/EmailCheck.java, backend/src/main/java/com/devu/backend/controller/validation/EmailCheckValidator.java, backend/src/main/resources/application.yml, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java
회원가입 시 이메일 인증을 위해 들어오는 email 정보에 대한 validation 추가(yu.ac.kr or ynu.ac.kr)
=> feat:UserController Email Validation 추가

backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java
fix:PostControllerTest error in Jenkins
=> fix:PostControllerTest error in Jenkins

backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java
=> none-fix:error

backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java
현재 Jenkins에서 배포 시 PostControllerTest에서 깨지는 현상이 파일 업로드 관련 예외 때문임을 발견했습니다.
해당 테스트 코드에서 해당 부분은 주석처리 하였습니다.
현재 테스트 코드 메서드의 경우 하나의 메서드가 너무 많은 작업을 진행하기에 추후에 테스트 기능별로 메서드를 세분화할 필요가 있어 보입니다!
간단한 작업이라 바로 머지하겠습니다
=> test:PostControllerTest 수정

README.md
=> docs:README.md 수정

frontend/.env.production, frontend/package.json, frontend/src/components/Register/Register.js
- 서버 주소 변경 https://api.devu.site:8081/
- 회원가입 폼 `이름` -> `닉네임` 문구 변경
- 회원가입 이메일 인증 백엔드에서 바뀐 부분이 있어 프론트에서도 백엔드에 맞게 수정(데이터 포맷 `formData`-> `JSON`으로 변경)
=> fix: 서버 주소 변경, 회원가입 이메일 인증 JSON 변경

backend/src/docs/asciidoc/api.adoc, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java, backend/src/test/java/com/devu/backend/service/UserServiceTest.java
test: 로그아웃 테스트 및 문서화
- Userservice에 logoutProcess test
- UserController에 logout test 및 문서화
=> test: 로그아웃 테스트

backend/src/docs/asciidoc/api.adoc, backend/src/main/java/com/devu/backend/api/comment/CommentApiController.java, backend/src/main/resources/static/docs/api.html, backend/src/test/java/com/devu/backend/api/comment/CommentApiControllerTest.java, backend/src/test/java/com/devu/backend/controller/user/UserControllerTest.java, backend/src/test/java/com/devu/backend/service/UserServiceTest.java
docs: Comment API 문서화
- CommentApiController 리팩터링
- Comment API 문서화 및 test 수정
- assert 간소화(ex) assertequals( object == true) => asserttrue(object))
- viewComment 삭제
- docs 코드 추가
=> docs: Comment API 문서화

backend/BOOT-INF/classes/static/docs/api.html, backend/src/docs/asciidoc/api.adoc, backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java
docs: Post 문서화 수정
- Post 문서화 수정
=> docs: Post 문서화 수정

backend/src/main/java/com/devu/backend/repository/comment/CommentRepository.java, backend/src/main/java/com/devu/backend/service/CommentService.java, backend/src/main/java/com/devu/backend/service/PostService.java, backend/src/test/java/com/devu/backend/api/comment/CommentApiControllerTest.java
=> fix: 대댓글 수정

backend/src/main/java/com/devu/backend/service/EmailService.java
=> fix:비밀번호 변경 api 수정

backend/src/main/java/com/devu/backend/service/EmailService.java
=> fix:conflict

backend/src/main/java/com/devu/backend/service/EmailService.java
=> fix:비밀번호 수정 주소 링크

backend/src/test/java/com/devu/backend/controller/post/PostControllerTest.java, backend/src/test/java/com/devu/backend/service/UserServiceTest.java
fix:테스트로 인한 배포 빌드 실패
테스트 코드 삭제
=> fix:테스트로 인한 배포 빌드 실패

backend/src/main/java/com/devu/backend/service/PositionService.java
fix: 채용정보 관련 수정
- 카카오 url 수정
- Schedule 적용
- log 제거
=> fix: 채용정보 관련 수정

backend/src/main/java/com/devu/backend/controller/user/UserKeyRequestDto.java
=> fix:UserKeyReqDto

backend/src/main/java/com/devu/backend/entity/post/Post.java
=> update:orphanRemoval true
